name: vehicle_recognizer
channels:
  - conda-forge
  - defaults
dependencies:
  - tensorflow==2.1.0
  - jupyterlab==1.0.2
  - pydrive==1.3.1
  - keras==2.3.1
  - matplotlib
  - pandas
  - numpy
  - pillow
  - scikit-learn
  - pydot
